#!/usr/bin/env python3
"""
Builds the résumé fonts and their width tables (docs/RESUME_TEMPLATE_IMPLEMENTATION_AUDIT.md).

  pip install fonttools
  python3 scripts/resume-fonts.py <dir-with-google-fonts-ttfs>

Input: the Google Fonts TTFs of Inter, Source Serif 4 and IBM Plex Sans (OFL; e.g. from the
@expo-google-fonts packages). Output:
  public/fonts/resume/<family>-<weight>.ttf   subset to Latin, Latin-1, Latin Extended-A/B,
                                               punctuation and currency, with kerning and
                                               ligatures removed — the browser preview and the PDF
                                               must place every glyph at the same advance
  src/domain/resume/fontMetrics.generated.ts  advance widths (1/1000 em) the layout engine uses
"""
import os, sys, json
from fontTools import subset
from fontTools.ttLib import TTFont

SRC = sys.argv[1]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_FONTS = os.path.join(ROOT, "public", "fonts", "resume")
OUT_TS = os.path.join(ROOT, "src", "domain", "resume", "fontMetrics.generated.ts")
FILES = {
    "inter-400": "Inter_400Regular.ttf", "inter-600": "Inter_600SemiBold.ttf", "inter-700": "Inter_700Bold.ttf",
    "serif-400": "SourceSerif4_400Regular.ttf", "serif-600": "SourceSerif4_600SemiBold.ttf", "serif-700": "SourceSerif4_700Bold.ttf",
    "plex-400": "IBMPlexSans_400Regular.ttf", "plex-600": "IBMPlexSans_600SemiBold.ttf",
}
RANGES = [(0x20, 0x7E), (0xA0, 0x24F), (0x2010, 0x2027), (0x2030, 0x203A), (0x20AC, 0x20AC), (0x20B9, 0x20B9), (0x2122, 0x2122)]
UNICODES = [c for a, b in RANGES for c in range(a, b + 1)]

def find(name):
    for dp, _, fs in os.walk(SRC):
        if name in fs:
            return os.path.join(dp, name)
    sys.exit(f"missing {name}")

os.makedirs(OUT_FONTS, exist_ok=True)
metrics = {}
for key, fname in FILES.items():
    font = TTFont(find(fname))
    opts = subset.Options()
    opts.layout_features = []      # no kerning, no ligatures
    opts.hinting = False
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    opts.drop_tables += ["GPOS", "GSUB", "kern"]
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=UNICODES)
    sub.subset(font)
    out = os.path.join(OUT_FONTS, f"{key}.ttf")
    font.save(out)
    f = TTFont(out)
    upm = f["head"].unitsPerEm
    cmap = f.getBestCmap()
    hmtx = f["hmtx"]
    widths = {}
    for cp in UNICODES:
        g = cmap.get(cp)
        if g is not None:
            widths[cp] = round(hmtx[g][0] * 1000 / upm)
    os2 = f["OS/2"]
    # Contiguous runs keep the table small: [start, [w, w, …]].
    runs, cur = [], None
    for cp in sorted(widths):
        if cur and cp == cur[0] + len(cur[1]):
            cur[1].append(widths[cp])
        else:
            cur = [cp, [widths[cp]]]
            runs.append(cur)
    metrics[key] = {
        "ascender": round(os2.sTypoAscender * 1000 / upm),
        "descender": round(os2.sTypoDescender * 1000 / upm),
        "fallback": widths.get(0x6E, 500),
        "runs": runs,
    }
    print(key, os.path.getsize(out), "bytes,", len(widths), "glyphs")

with open(OUT_TS, "w") as fh:
    fh.write("// Generated by scripts/resume-fonts.py — do not edit. Advance widths in 1/1000 em.\n")
    fh.write("export const FONT_METRICS = " + json.dumps(metrics, separators=(",", ":")) + " as const;\n")
print("wrote", OUT_TS)
