import Image from "next/image";
import Link from "next/link";
import { cn } from "@/lib/cn";

/**
 * The official WonderJobs brand assets (`public/brand/`, regenerated by `scripts/brand-assets.mjs`
 * from the source artwork). Two inks exist because the wordmark's neutral grey disappears on the
 * product's dark surfaces: pass `tone="dark"` on anything sitting on ink/night backgrounds.
 */
export type BrandTone = "light" | "dark";

const MARK = { src: "/brand/wonder-mark.png", width: 138, height: 128 };
const LOGO: Record<BrandTone, string> = { light: "/brand/wonderjobs-logo-light.png", dark: "/brand/wonderjobs-logo-dark.png" };
const LOGO_SIZE = { width: 527, height: 96 };
const LOCKUP: Record<BrandTone, string> = { light: "/brand/wonderjobs-lockup-light.png", dark: "/brand/wonderjobs-lockup-dark.png" };
const LOCKUP_SIZE = { width: 1024, height: 240 };

/** The butterfly on its own, sized by height. Decorative by default — give the wrapper the label. */
export function WonderMark({ className, size = 28, alt = "" }: { className?: string; size?: number; alt?: string }) {
  return <Image src={MARK.src} alt={alt} aria-hidden={alt ? undefined : true} width={MARK.width} height={MARK.height} style={{ height: size, width: "auto" }} className={cn("select-none", className)} priority unoptimized />;
}

/** Mark + wordmark. `compact` drops the wordmark (collapsed sidebar, small screens). */
export function WonderLogo({ href = "/", className, compact = false, size = 28, tone = "light" }: { href?: string | null; className?: string; compact?: boolean; size?: number; tone?: BrandTone }) {
  const content = compact ? (
    <WonderMark size={size} />
  ) : (
    <Image src={LOGO[tone]} alt="WonderJobs" width={LOGO_SIZE.width} height={LOGO_SIZE.height} style={{ height: size, width: "auto" }} className="select-none" priority unoptimized />
  );
  if (!href) return <span className={cn("inline-flex items-center", className)}>{content}</span>;
  return (
    <Link href={href} className={cn("inline-flex items-center", className)} aria-label="WonderJobs home">
      {content}
    </Link>
  );
}

/** Full lockup including the "Find. Grow. Belong." tagline — for hero and brand moments, not navigation. */
export function WonderLockup({ className, size = 96, tone = "light" }: { className?: string; size?: number; tone?: BrandTone }) {
  return <Image src={LOCKUP[tone]} alt="WonderJobs — Find. Grow. Belong." width={LOCKUP_SIZE.width} height={LOCKUP_SIZE.height} style={{ height: size, width: "auto" }} className={cn("select-none", className)} priority unoptimized />;
}
